sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.2

script: ./script/cibuild.sh

addons:
  code_climate:
    repo_token: 255471a43e3a15d0be710482a929e717605dd1d9a6c4729809d37d1aea8fe4f3
  apt:
    packages:
      - libcurl4-openssl-dev

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler # caching bundler gem packages will speed up build