default: &default
  socket: /tmp/.s.PGSQL.5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: russchenmedia_development

test:
  <<: *default
  database: russchenmedia_test

production:
  adapter: postgresql
  host: localhost
  username: user
  database: russchenmedia_production
  pool: 5
  timeout: 5000
